# Generated by Django 3.2.8 on 2021-11-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20211029_1256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='image',
            name='img_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
