# Generated by Django 3.2.8 on 2021-11-02 07:15

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20211102_0611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['img_number']},
        ),
        migrations.AddField(
            model_name='place',
            name='content',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
